### ISSUE TITLE
Error code 404

### ISSUE THREAD

**Issue by pjhavariotis** [TURROKS/CVE_Prioritizer#17]
I'm getting "Error code 404" when I enter my NVD API key.
![image](https://github.com/TURROKS/CVE_Prioritizer/assets/11760210/b29d0f96-392e-4578-944b-2724902fc90a)

If I remove the API key, everything works like a charm!
![image](https://github.com/TURROKS/CVE_Prioritizer/assets/11760210/100080c1-98cb-4c45-8bd5-4f4363c66963)

**Comment by pjhavariotis** [comment]
I have just realized that this glitch was due to my API key.

**Comment by Tyrell20** [comment]
Hello @TURROKS @pjhavariotis 

I have the same issue:
- without API Key no error;
![image](https://github.com/TURROKS/CVE_Prioritizer/assets/64137969/4256daa3-96d9-4a2e-b4cb-cfcd340573ec)


- with NIST API Key 404 error.
![image](https://github.com/TURROKS/CVE_Prioritizer/assets/64137969/f78e766a-fad7-4db3-8051-125b3d021f21)



I tried with **different API Keys**, same issue.

What could I check for?

Thank you
