### ISSUE TITLE
Including CVSSv4

### ISSUE THREAD

**Issue by andreassyz** [TURROKS/CVE_Prioritizer#22]
Hi There!
I see that it is currently CVSSv3.1, will there be plans to incorporate v4.0?
Thanks in advance!

**Comment by TURROKS** [comment]
Hi @andreassyz absolutely, I haven't found an example from NIST NVD that includes CVSSv4 yet. Once I find one I will add the required mappings to the script. 

Best,
Mario

**Comment by TURROKS** [comment]
@andreassyz it does not look like NIST has updated their API to include CVSS4 yet, I will prioritize this update once NVD starts releasing CVEs with CVSS4
