### ISSUE TITLE
NVD api key header is wrong

### ISSUE THREAD

**Issue by gollima** [TURROKS/CVE_Prioritizer#4]
Change the header to the NVD api key to api_key

**Comment by TURROKS** [comment]
Hi @gollima, thanks for bringing this to my attention, would you mind sharing a link to the documentation where it mentions that format, I was following [NIST's API Guide](https://nvd.nist.gov/developers/start-here) and it mentions **apiKey:{key value}**
 
![Screenshot from 2023-06-03 12-22-54](https://github.com/TURROKS/CVE_Prioritizer/assets/16016384/e143e001-e538-4aea-831b-a2f48c2b75ac)

Thanks,
