### ISSUE TITLE
Exporting of csv report

### ISSUE THREAD

**Issue by dr4lekhine** [TURROKS/CVE_Prioritizer#5]
Hi,

First of all, kudos for the project, a good tool.

Could you add a feature to export the results in screen to something like a csv report?.

Thanks in advance.

Regards,

**Comment by TURROKS** [comment]
Hey there, thanks for creating an issue for this. I forgot to add this to the documentation, but there's an option to generate a CSV report. 

You can use the -o flag and provide a file_name to create a report, and it will output the verbose details.

Best
Mario
