### ISSUE TITLE
Bulk/batch mode with file giving errors

### ISSUE THREAD

**Issue by dr4lekhine** [TURROKS/CVE_Prioritizer#6]
Hello,

When I try to check several CVEs from a file, I see the following error:

![image](https://github.com/TURROKS/CVE_Prioritizer/assets/72524642/4ac479eb-ce14-4e26-be79-b2e0a152bdd9)

It´s probably related to the fact that the "vulns.txt" file contains a lots of CVE, in this case 2337 lines/CVEs, and the differents API from CVSS, EPSS and CISA KEV are rejecting the multiple queries.

[vulns.txt](https://github.com/TURROKS/CVE_Prioritizer/files/11637421/vulns.txt)

I wasn´t able to test this in another environment because I´m traveling in other country and don´t have another system at handy, but if a put few lines in file, works good. Example:

![image](https://github.com/TURROKS/CVE_Prioritizer/assets/72524642/e7e1afca-16ec-4c6e-a925-ee15b5787c6f)

So, probably you will need to create a logic to do in staggered batches. Would be that possible? :)

The details of my current environment are the following: 

Windows Subsystem for Linux (WSL)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Also, check the output of apt list --installed (upon apt update -y && apt upgrade -y)

[apt_list_installed.txt](https://github.com/TURROKS/CVE_Prioritizer/files/11637474/apt_list_installed.txt)

Also, .env file already have the NVD API key

Thanks in advance.

Regards.

**Comment by TURROKS** [comment]
Hey @dr4lekhine thanks for bringing this to my attention! 

I have added a few checks and balances to the code to try to avoid this from happening when working with large numbers of CVES.

I tested the new updates by running the script on your vulns.txt file and Im happy to share that it completed without any issues, here are the results [dr4lekhine_cves.csv](https://github.com/TURROKS/CVE_Prioritizer/files/11642195/dr4lekhine_cves.csv)

Best,
Mario
